### ISSUE TITLE
Cas Plugin is broken as of 2.266 due to Acegi migration to Spring Security

### ISSUE THREAD

**Issue by vwbusguy** [jenkinsci/cas-plugin#5]
Jenkins 2.266 replaced acegi with spring-xstream for security, ref. https://www.jenkins.io/blog/2020/11/10/spring-xstream/ .

The CAS plugin now fails on startup:

```
2020-11-10 22:50:03.529+0000 [id=33]	WARNING	jenkins.model.Jenkins$5#runTask: Finalizing set up failed perhaps due to plugin dependency issues
java.lang.ClassNotFoundException: hudson.util.spring.BeanBuilder
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1387)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1342)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1089)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
Caused: java.lang.NoClassDefFoundError: hudson/util/spring/BeanBuilder
```

This causes all views to attempt to be rendered with anonymous ACLs, potentially causing all of Jenkins web endpoints to result in an error page.

**Comment by vwbusguy** [comment]
This appears to be related to https://github.com/jenkinsci/cas-plugin/pull/4

**Comment by vwbusguy** [comment]
FYI - It is now working for me with the plugin from the PR: https://github.com/jenkinsci/cas-plugin/pull/4#issuecomment-727654013

**Comment by vwbusguy** [comment]
Works for me now with #4

**Comment by fcrespel** [comment]
Release 1.5.0 is out, note that it may take a few hours to appear in the plugins page and update center.
